# Generated by Django 5.0.6 on 2024-07-26 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('Caption', models.CharField(max_length=100)),
            ],
        ),
    ]
