# Generated by Django 5.0.6 on 2024-09-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='snapshot_image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
