# Generated by Django 5.0.6 on 2024-09-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_image',
        ),
        migrations.AddField(
            model_name='post',
            name='blog_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
