# Generated by Django 5.0.6 on 2024-09-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_blog_image_post_blog_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_number',
        ),
    ]
