# Generated by Django 5.0.6 on 2024-09-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_date_alter_post_body_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='para1',
            field=models.TextField(default='para1'),
        ),
        migrations.AddField(
            model_name='post',
            name='para10',
            field=models.TextField(default='para10'),
        ),
        migrations.AddField(
            model_name='post',
            name='para2',
            field=models.TextField(default='para2'),
        ),
        migrations.AddField(
            model_name='post',
            name='para3',
            field=models.TextField(default='para3'),
        ),
        migrations.AddField(
            model_name='post',
            name='para4',
            field=models.TextField(default='para4'),
        ),
        migrations.AddField(
            model_name='post',
            name='para5',
            field=models.TextField(default='para5'),
        ),
        migrations.AddField(
            model_name='post',
            name='para6',
            field=models.TextField(default='para6'),
        ),
        migrations.AddField(
            model_name='post',
            name='para7',
            field=models.TextField(default='para7'),
        ),
        migrations.AddField(
            model_name='post',
            name='para8',
            field=models.TextField(default='para8'),
        ),
        migrations.AddField(
            model_name='post',
            name='para9',
            field=models.TextField(default='para9'),
        ),
    ]
