# Generated by Django 5.0.6 on 2024-09-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_para1_post_para10_post_para2_post_para3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='para1',
            field=models.TextField(blank=True, default='para1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='para10',
            field=models.TextField(blank=True, default='para10'),
        ),
        migrations.AlterField(
            model_name='post',
            name='para2',
            field=models.TextField(blank=True, default='para2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='para3',
            field=models.TextField(blank=True, default='para3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='para4',
            field=models.TextField(blank=True, default='para4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='para5',
            field=models.TextField(blank=True, default='para5'),
        ),
        migrations.AlterField(
            model_name='post',
            name='para6',
            field=models.TextField(blank=True, default='para6'),
        ),
        migrations.AlterField(
            model_name='post',
            name='para7',
            field=models.TextField(blank=True, default='para7'),
        ),
        migrations.AlterField(
            model_name='post',
            name='para8',
            field=models.TextField(blank=True, default='para8'),
        ),
        migrations.AlterField(
            model_name='post',
            name='para9',
            field=models.TextField(blank=True, default='para9'),
        ),
    ]
